# Generated by Django 4.1.7 on 2023-04-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('hydraulic_rating', models.IntegerField()),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('fuel_type', models.CharField(choices=[('G', 'Gasoline'), ('D', 'Diesel'), ('K', 'Kerosene'), ('L', 'LP Gas')], default='G', max_length=1)),
                ('engine_information', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('water_dependancy', models.IntegerField()),
                ('growing_season', models.CharField(max_length=10)),
                ('optimal_growing_conditions', models.CharField(max_length=100)),
                ('average_growth_time', models.CharField(max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
