# Generated by Django 4.1.7 on 2023-04-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_equipment_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.animal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.crops'),
        ),
        migrations.AddField(
            model_name='comment',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.equipment'),
        ),
    ]
