# Generated by Django 4.1.7 on 2023-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_crops_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growing_season',
            field=models.CharField(max_length=50),
        ),
    ]
