# Generated by Django 4.1.7 on 2023-04-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_water_dependancy_crop_water_dependency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='optimal_growing_conditions',
            new_name='hardiness_zone',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='water_dependency',
            new_name='irrigation_needs',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='growing_season',
            new_name='planting_season',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='average_growth_time',
        ),
        migrations.AddField(
            model_name='crop',
            name='maturity_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.crop'),
        ),
        migrations.AddField(
            model_name='photo',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.equipment'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.animal'),
        ),
    ]
