# Generated by Django 4.1.7 on 2023-04-19 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_rename_optimal_growing_conditions_crop_hardiness_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='user',
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
