# Generated by Django 4.1.7 on 2023-04-19 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_remove_animal_user_animal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='user',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='user',
        ),
        migrations.AddField(
            model_name='crop',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
